### ISSUE TITLE
Cannot listen to the controller state (e;.g. if animation finished)

### ISSUE THREAD

**Issue by RobinLbt** [funwithflutter/flutter_confetti#30]
It would be very nice to be able to listen to the state of a Confetti controller.
For example in one of my apps I create confetti controller on the fly and there is no way to remove them when the animation is done like you can do with AnimationController when you listen to the statut of the animation.

**Comment by WieFel** [comment]
Same problem here!
```dart
confettiController.addListener(() {
  print("FINISHED!");
});
```
The added listener doesn't seem to get called at all.

**Comment by WieFel** [comment]
I have the same problem. The listener is only called when animation starts.
Also, it is not possible to access `ConfettiControllerState` in order to compare the current state of the controller with some value.

**Comment by WieFel** [comment]
Something seems to be wrong with the controller state and/or the listener handling.
If I use the example code https://github.com/funwithflutter/flutter_confetti/blob/master/example/lib/main.dart and add a listener to the top center controller like so:
```dart
  @override
  void initState() {
    _controllerCenter =
        ConfettiController(duration: const Duration(seconds: 10));
    _controllerCenterRight =
        ConfettiController(duration: const Duration(seconds: 10));
    _controllerCenterLeft =
        ConfettiController(duration: const Duration(seconds: 10));
    _controllerTopCenter =
        ConfettiController(duration: const Duration(seconds: 10));
    _controllerBottomCenter =
        ConfettiController(duration: const Duration(seconds: 10));

    _controllerTopCenter.addListener(() {
      print("STATE CHANGED: " + _controllerCenter.state.toString());
    });
    super.initState();
  }
```
When tapping the top center button I get the following output:
```
I/flutter ( 5382): STATE CHANGED: ConfettiControllerState.stopped
```
Which is really strange because I would expect to get `playing` state when the animation is started.
Besides that, tt is the only output I get. When the animation is finished, there is no more output from the listener.
