### ISSUE TITLE
Overlaying the conefetti over other items

### ISSUE THREAD

**Issue by CedYF** [funwithflutter/flutter_confetti#4]
Hey,

Love the plugin. But I'm trying to overlay the confetti over items. Instead it always appear behind elements in stack or scaffold.

Anyway to move the confetti to the front layer?

**Comment by funwithflutter** [comment]
Hey. Thanks for bringing this up. I added an optional child widget to the ConfettiWidget that you can pass in. I also changed the way that the painting is happening so that it paints to the foreground above its child widget. So you an either wrap everything under the ConfettiWidget(child: YourApp), or alternatively you can use a Stack, and then add ConfettiWidget as the last child in the stack to make sure it get's painted above the rest of the widgets. I tested both and it works. Note that this won't paint above the appbar (scaffold) - as the appbar will be painted above everything else. If you need to achieve that affect then you'll have to put the appbar in you Stack, and not use the appbar parameter provided in the scaffold.
